// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC86iW8GdUQAnRarUbbkqBeLBK0UccyCV8',
    appId: '1:887312305836:web:4a2da4bbd6f1b59082d909',
    messagingSenderId: '887312305836',
    projectId: 'food-waste-se',
    authDomain: 'food-waste-se.firebaseapp.com',
    storageBucket: 'food-waste-se.firebasestorage.app',
    measurementId: 'G-D7KKZ5FHDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDknralGg_0Hy_8OWOEFKUO1X3RvGe6SsE',
    appId: '1:887312305836:android:2be491412297311e82d909',
    messagingSenderId: '887312305836',
    projectId: 'food-waste-se',
    storageBucket: 'food-waste-se.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP6cL785GOafLTQ8m-eD6xH8RzwFRvI3E',
    appId: '1:887312305836:ios:0de3b7ce6af4d7a182d909',
    messagingSenderId: '887312305836',
    projectId: 'food-waste-se',
    storageBucket: 'food-waste-se.firebasestorage.app',
    iosBundleId: 'com.example.foodeWasteApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP6cL785GOafLTQ8m-eD6xH8RzwFRvI3E',
    appId: '1:887312305836:ios:0de3b7ce6af4d7a182d909',
    messagingSenderId: '887312305836',
    projectId: 'food-waste-se',
    storageBucket: 'food-waste-se.firebasestorage.app',
    iosBundleId: 'com.example.foodeWasteApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC86iW8GdUQAnRarUbbkqBeLBK0UccyCV8',
    appId: '1:887312305836:web:44f88697016c3e9082d909',
    messagingSenderId: '887312305836',
    projectId: 'food-waste-se',
    authDomain: 'food-waste-se.firebaseapp.com',
    storageBucket: 'food-waste-se.firebasestorage.app',
    measurementId: 'G-J6TT4J5FDE',
  );
}
